ci:
  autoupdate_schedule: "quarterly"
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.11
  hooks:
    - id: ruff
      args: [--fix]
    - id: ruff-format
- repo: https://github.com/adamchainz/blacken-docs
  rev: 1.19.1
  hooks:
    - id: blacken-docs
      files: ^docs/.*\.(rst|md)$
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: v2.6.0
  hooks:
    - id: pyproject-fmt
