name: CI (with pixi)

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

defaults:
  run:
    shell: pixi run bash -e {0}

jobs:
  test:
    name: ${{ matrix.os }}, 🐍=${{ matrix.environment}}, ${{ matrix.mamba-executable }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        environment: [
          py311,
          py312,
          py313,
          py314,
          py311-openeye,
          py312-openeye,
          py313-openeye,
          py311-ambertools,
          py312-ambertools,
          py313-ambertools,
          py311-openeye-ambertools,
          py312-openeye-ambertools,
          py313-openeye-ambertools,
          typing,
        ]
        mamba-executable: ["pixi"]

    env:
      OE_LICENSE: ${{ github.workspace }}/oe_license.txt
      COV: --cov=openff/utilities --cov-report=xml --cov-append

    steps:
    - uses: actions/checkout@v6

    - name: Set up environment with pixi
      if: matrix.mamba-executable == 'pixi'
      uses: prefix-dev/setup-pixi@v0.9.4
      with:
        environments: ${{ matrix.environment }}
        activate-environment: ${{ matrix.environment }}
        frozen: true

    - name: Check AmberTools Missing
      if: ${{ !contains(matrix.environment, 'ambertools') }}
      run: python -c "from shutil import which; assert which('sqm') is None"

    - name: Check AmberTools installation
      if: ${{ contains(matrix.environment, 'ambertools') }}
      run: python devtools/scripts/assert_ambertools_found.py

    - name: Check OpenEye Toolkits missing
      if: ${{ !contains(matrix.environment, 'openeye') }}
      run: python devtools/scripts/assert_openeye_not_found.py

    - name: Run a test with OpenEye toolkits installed but NOT licensed
      if: ${{ contains(matrix.environment, 'openeye') }}
      run: pixi run run_edge_case

    - name: License OpenEye
      if: ${{ contains(matrix.environment, 'openeye') }}
      run: |
        echo "${SECRET_OE_LICENSE}" > ${OE_LICENSE}
        python -c "from openeye import oechem; assert oechem.OEChemIsLicensed()"
      env:
        SECRET_OE_LICENSE: ${{ secrets.OE_LICENSE }}

    - name: Run mypy
      if: ${{ matrix.environment == 'typing' }}
      run: pixi run run_mypy

    - name: Run unit tests
      if: ${{ matrix.environment != 'typing' }}
      run: pixi run run_tests

    - name: Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
